name: Backend CI Pipeline

on:
  pull_request:
    branches:
      - main
    paths:
      - 'starter/backend/**'
  workflow_dispatch:

jobs:
  lint-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v4

      - name: Configure Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Linting Dependencies
        run: |
          cd starter/backend
          pip install pipenv flake8
          pipenv install --dev

      - name: Execute Linting
        run: |
          cd starter/backend
          pipenv run lint

  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v4

      - name: Configure Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Testing Dependencies
        run: |
          cd starter/backend
          pip install pipenv flake8
          pipenv install --dev

      - name: Run Unit Tests
        run: |
          cd starter/backend
          pipenv run test

  build-docker:
    runs-on: ubuntu-latest
    needs: [lint-code, run-tests]

    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v4

      - name: Set Up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Initialize Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          cd starter/backend
          docker build --tag mp-backend:latest .
